## Python Modules and Libraries

> ### Introduction
> Before diving into the tehcnical details, lets understand the basic concepts of modules and libraries in Pytyhon

> **What is module?**
>
>A module is a file containing Python code. This code can be in the form of functions, classes, or variables. A module is a .py file that can be executed or imported into other modules or scripts
>
>**What is a Library/Package?**
>
>A library (or package) is a collection of related modules grouped together. Libraries provide a way to organize and package related modules into a single directory hierarchy.Python has a vast standard library that provides modules and packages to handle a variety of tasks.
>
> **Why use modules and library?**
>
> - **Code reusability**: Instead of writing the same code again and again, we can save the code in a module and import it whenever needed.
>
> - **Organized code**: Modules and libraries help in organizing the code in a better way, making it more readable and maintainable.
>
> - **Efficiency**: Using pre-built libraries can save time and effort, as they are optimized and tested by a large community of developers.
>
> - **Avoiding namespace conflicts**: By using modules, we can avoid conflicts between variable names, function names, and class names.

> ### Python Module
>
> In Python, a module essentially a file containing Python code. This code can be in the  form of function, classes, or variables, and can also include runnable code. The primary purpose of a module is to organize and encapsulate code to promote reusability across different programs and projects.

> ### Creating a module
>
> Creating a module in Python is as simple as create a Python file.
>
> For instance, if you create a file named `mymodule.py` and define a function `say_hello()` within it, `mymodule.py` becomes a module, and `say_hello` is a function that can be imported and used in other Python scripts or notebooks.
>
> Lets assume the content of `mymodule.py` is:

In [19]:
def say_hello():
    return "Hello World!"

> Now, lets see how we can import and use this function from the module.

> ### Importing a Module
>
> Once you have a module, you can use its functionalities in another script or notebook by importing it. There are various ways to import modules in Python.

> 1. Using the `import` statement You can import the entire module using the `import` statement followed by the module name (without the `.py` extension).

In [ ]:
import mymodule

mymodule.say_hello()

> 2. Using the `from...import...` statement if you ony want to import a specific function or class from a module, you can use the `from...import...` statement.

In [ ]:
from module import say_hello

say_hello()

> 3. Aliasing modules sometimes, for the sake of convenience or to avoid naming conflicts, you might want to give a module (or a function) a different name when importing. This can be achieved using the `as` keyword

In [ ]:
import mymodule as mm

mm.say_hello()

> Lets see some of these import methods in action

In [1]:
# module basic math
"""
This is an example of docstring to demonstrate a module.
"""

# addition function
def add(a, b):
    """Return the sum of two numbers."""
    return a + b

# substract function
def subtract(a, b):
    """Return the difference of two numbers."""
    return a - b

# multiply function
def multiply(a, b):
    """Return the product of two numbers."""
    return a * b

# divide function
def divide(a, b):
    """
    Return the quotient of two numbers. 
    If division by zero is attempted, return a message.
    """
    if b == 0:
        return "Error: Division by zero!"
    return a / b

In [2]:
import basic_math
from basic_math import subtract
from basic_math import multiply

In [3]:
basic_math?

Type:        module
String form: <module 'basic_math' from 'C:\\Users\\Aldi Fauzan\\latihan-py\\MES\\basic_math.py'>
File:        c:\users\aldi fauzan\latihan-py\mes\basic_math.py
Docstring:   This is an example of docstring to demonstrate a module.

In [6]:
print(basic_math.add(10,5))
print(subtract(10,5))
print(multiply(10,2))

15
5
20


> ### BUILT-IN MODULES AND LIBRARIES IN PYTHON
> Python comes with a vast standard library that provides a rich set of modules and packages to handle a wide variety of tasks. These built-in modules are written in C and integrated with the Python interpreter, making them both fast and efficient.
>
> Some commonly used built-in modules include:
>
> - `math` : Provides mathematical functions and operations
> - `datetime` : Offers classes for manipulating dates and times.
> - `os` : Offers a way of using operating system-dependent functionality like reading or writing to the file system.
> - `sys` : Provides access to some variables used or maintained by the interpreter and to functions that interact strongly with the interpreter.
> - `json` : Used for encoding and decoding JSON data.

> ### Using the `math` module
>
> The `math` modules provides mathematical functions, trigonometric, logarithmic, and other operations.
>
> Here are a few examples of what you can do with the `math` modules.

In [7]:
import math

In [51]:
# calculate the square root of a number
sqrt_val = math.sqrt(25)

# calculate the factorial of a number
factorial_math = math.factorial(5)

# calculate the cosine of an angle (angle in radians)
cos_val = math.cos(math.radians(45))

# calculate the power
pow_val = math.pow(5,2)

In [52]:
print(sqrt_val)
print(factorial_math)
print(cos_val)
print(pow_val)

5.0
120
0.7071067811865476
25.0


> ### Using the `random` module
>
> The `random` module in Python provides functions to generate random numbers for various purposes
>
> This modules is particularly useful in scenarios like simulations, games, testing, and more.

In [10]:
import random

In [11]:
print(random.randint(10,20))

15


In [12]:
for i in range(3):
    print(random.randint(10,15))

10
13
13


In [13]:
fruits = ['apple', 'banana', 'cherry', 'orange']
print(random.choice(fruits))

banana


In [14]:
print(random.sample(fruits,3))

['apple', 'banana', 'orange']


> ### Using the `datetime` module
>
> The `datetime` module supplies classes to work with date and time.
>
> These classes provide a number of functions to deal with dates, times, and time intervals.

In [36]:
import datetime

In [37]:
current_datetime = datetime.datetime.now()
current_date = datetime.date.today()
specific_date = datetime.date(2023, 9, 20)
date_diff = specific_date - current_date

In [38]:
print(current_datetime)
print(current_date)
print(specific_date)
print(date_diff)

2023-10-06 08:11:45.233903
2023-10-06
2023-09-20
-16 days, 0:00:00


> ### Benefit of Using Modules and Libraries
>
> Modules and libraries play a crucial role in the development process in Python
>
> They offer several benefits that make the life of developer easier and the development process more efficient. Here are some of the primary benefits of using modules and libraries in Python:

> 1. **Code Reusability**: One of the main advantages of using modules and libraries is the reusability of code. Developers can write functions and classes in modules and reuse them across multiple project without rewriting the code.
>
> 2. **Efficiency**: Many libraries in Python are optimized for performance. By using these libraries, developers can achive faster executing times without having to optimize the code manually.
>
> 3. **Maintainability**: Breaking down a large codebase into smaller modules makes the code more organized and easier to maintain. If a bug is found in a module, it can be fixed in that module without affecting other parts of the applications.
>
> 4. **Collaborations**: Modules allow multiple developers to work on different parts of an application simultaneously. Each developer can work on a separate module, which reduces the chances of merge conflicts.
>
> 5. **Rapid Development**: With the availability of numerous library in Python, developers can quickly develop applications by leveraging pre-built functions and classes. This significantly reduces the development time.
>
> 6. **Standardization**: Many Python libraries follow best practices and coding standards. By using these libraries, developers can ensure that their application adhere to industry standards
>
> 7. **Extensibility**: Modules provide a way to extend the functionality of an application. Developers can add new features to an application by simply importing and integrating new modules.

>### MODULE VS PACKAGE VS LIBRARIES
>
>**1. Module**
>
>In Python, a module refers to a file containing Python code, Modules serve as containers for functions, classes, and variables, allowing for code organization and reusability. By breaking down code into modules, developers can maintain a clean and modular codebase. Modules are imported using the import statement, enabling access to their defined functions and classes, promoting code modularity and readability.
>
>**2. Package**
>
>Packages are directories that contain multiple Python modules. They provide a hierarchical structure for organizing related modules. A package must include a special file called **init.py**, marking it as a package. Packages help prevent naming conflicts and enable developers to manage large-scale projects efficiently. They allow for logical organization and grouping of modules, creating a more structured codebase.
>
>**3. Libraries**
>
>Libraries in Python are collections of modules and packages that extend the core functionalities of the language. They provide pre-written code and APIs for specific tasks, such as data manipulation, scientific computing, web development, machine learning, and more. Libraries enhance productivity by simplifying complex operations and providing high-level abstractions.

>### THIRD-PARTY LIBRARY
>
>While Python provides a rich set of built-in modules and packages, there are countless third-party libraries developed by the community that offer additional functionality and tools.
>
>These libraries can significantly speed up development by providing pre-written code for common tasks

> ### Installing libraries using pip
>
>Python provides a package manager called `pip` to install third-party libraries `pip` stands for "Pip Installs Packages" and is the default package manager for Python,
>
>To install a library using `pip`, you can use the following command in your terminal or command prompt:

In [ ]:
pip install library_name

>For example to install the popular data manipulation library `pandas`, you would use

In [40]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


> It's worth noting that some libraries may have dependencies on other libraries. When you install a library using pip, it will also install any required dependencies
automatically.

> Python boasts a vast ecosystem of third party libraries. Here we'll introduce some of the most popular and widely-used libraries across various domains:
>
>**numpy**: A library for numerical computing in Python. It provides support for large multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.
>
>**pandas**: A powerful data manipulation and analysis library. It provides data structures like DataFrames and Series for handling and analyzing structured data.

> ### Numerical Python (`numpy`)
>
>`numpy` is the foundational package for numerical computations in Python
>
>It provides support for large multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.
>
>An **array** is a collection of items usually of the same type, stored at contiguous memory locations. The idea is to represent multiple items of the same type using a single variable.

In [41]:
import numpy as np

In [42]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [43]:
range_arr = np.arange(0, 10, 2)
print(range_arr)

[0 2 4 6 8]


In [45]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [46]:
print(a+b)
print(a*b)
print(a/b)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


> ### Data Analysis Tool: `pandas`
>
>`pandas` provides powerful and flexible tools to analyze, filter, and visualize data.
>
>It introduces two primary data structures: Series and DataFrame.

In [22]:
import pandas as pd

In [23]:
vals = [1, 2, 3]
idxs = ['a', 'b', 'c'] 

In [24]:
s = pd.Series(vals,idxs)
print(s)

a    1
b    2
c    3
dtype: int64


In [25]:
# example of dataframe (two-dim labeled data structure)
data = {
    'Name' : ['Alice', 'Bob', 'Charlie'],
    'Age' : [25, 30, 35],
    'City' : ['New York', 'San Fransisco', 'Los Angeles']
}

In [26]:
df = pd.DataFrame(data)

In [27]:
df

Name  Age           City
0    Alice   25       New York
1      Bob   30  San Fransisco
2  Charlie   35    Los Angeles

>We can also import, open and transform text data directly to dataframe format using Pandas.
>
> We will be using the open dataset: https://data.pu.go.id/dataset/kepadatan-jalan-tahun-2020/resource/3a051732-a18c-475b-8452-aa9592276028#{}

In [28]:
df = pd.read_csv("https://data.pu.go.id/node/780/download")

In [29]:
df

Kd_Provinsi                   Provinsi  Luas_wilayah_km2  Jalan_Nasional  \
0           01                       Aceh         57,956.00       2,102.07    
1           03             Sumatera Utara         72,981.23       2,632.22    
2           06             Sumatera Barat         42,012.89       1,448.81    
3           09                       Riau         87,023.66       1,336.61    
4           10             Kepulauan Riau          8,201.72         586.83    
5           11                      Jambi         50,058.16       1,317.93    
6           13                   Bengkulu         19,919.33         792.61    
7           15           Sumatera Selatan         91,592.43       1,600.16    
8           16  Kepulauan Bangka Belitung         16,424.06         600.40    
9           17                    Lampung         34,623.80       1,292.21    
10          20                DKI Jakarta            664.01            -      
11          21                     Banten          9,662.92         564.89    
12          22                 Jawa Barat         35,377.76       1,789.20    
13          24                Jawa Tengah         32,800.69       1,518.09    
14          26              DI Yogyakarta          3,133.15         247.91    
15          28                 Jawa Timur         47,799.75       2,361.23    
16          30           Kalimantan Barat        147,307.00       2,117.57    
17          32          Kalimantan Tengah        153,564.50       2,002.08    
18          34           Kalimantan Timur        129,066.64       1,710.90    
19          35           Kalimantan Utara         75,467.70         585.16    
20          36         Kalimantan Selatan         38,744.23       1,204.30    
21          40                       Bali          5,780.06         629.39    
22          42        Nusa Tenggara Barat         18,572.32         934.55    
23          44        Nusa Tenggara Timur         48,718.10       1,857.91    
24          50             Sulawesi Utara         13,851.64       1,663.92    
25          51                  Gorontalo         11,257.07         748.60    
26          52            Sulawesi Tengah         61,841.29       2,373.40    
27          53             Sulawesi Barat         16,787.18         763.17    
28          54           Sulawesi Selatan         46,717.48       1,745.92    
29          56          Sulawesi Tenggara         38,067.70       1,497.81    
30          60                     Maluku         46,914.03       1,771.67    
31          61               Maluku Utara         31,982.50       1,203.34    
32          62                      Papua        319,036.05       2,636.73    
33          63                Papua Barat         99,671.63       1,326.38    
34         xxx                  Indonesia      1,913,578.68      46,963.97    

       Paved_JN  UnPaved_JN   Jalan_Prov     Paved_JP   UnPaved_JP  \
0     2,091.03       11.04     1,781.72     1,394.82       386.90    
1     2,632.22         -       3,048.50     2,737.56       310.94    
2     1,431.50       17.31     1,525.20     1,227.50       297.70    
3     1,305.59       31.02     2,799.81     1,766.46     1,033.35    
4       583.05        3.78       896.45       637.96       258.49    
5     1,317.93         -       1,032.84       878.30       154.54    
6       792.61         -       1,562.67     1,157.24       405.43    
7     1,600.16         -       1,513.65     1,134.42       379.23    
8       600.40         -         850.99       849.69         1.30    
9     1,292.21         -       1,693.27     1,583.69       109.58    
10         -           -            -            -            -      
11      564.89         -         762.03       759.00         3.03    
12    1,789.20         -       2,360.58     2,343.08        17.50    
13    1,518.09         -       2,404.74     2,404.74          -      
14      247.91         -         760.45       702.80        57.65    
15    2,361.23         -       1,421.0

### References

> 1. https://www.w3schools.com/python/python_modules.asp#gsc.tab=0
> 2. https://www.javatpoint.com/python-modules#:~:text=A%20module%20is%20a%20file,for%20the%20reuse%20of%20code
> 3. https://bridgewhy.com/python-powerhouse-exploring-modules-packages-and-libraries-for-wordpress-development/
> 4. https://docs.python.org/3/library/index.html
> 5. https://numpy.org/doc/stable/reference/index.html